branches:
  only: 
    - next
matrix:
  include:
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPackiOS="12"
        - Type="TypeScript"
      osx_image: xcode10.2
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_script:
        - pod repo update
        - cd ../demo && tns platform add ios@next
      script: 
        - cd ../publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build ios --bundle --env.uglify
    - language: android
      os: linux
      dist: trusty
      env:
        - WebPackAndroid="28"
        - Type="TypeScript"
      jdk: oraclejdk8
      before_install: nvm install 10
      before_script:
        - cd ../demo && tns platform add android@next
      script:  
        - cd ../publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env: 
        - WebpackAndroid="28"
        - Type="Angular"
      os: linux
      dist: trusty
      jdk: oraclejdk8
      before_install: nvm install 10
      before_script:
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../publish && sh pack.sh
        - cd ../demo-angular && npm i ../publish/package/*.tgz -s
        - tns build android --bundle --env.uglify --env.snapshot --env.aot
    - os: osx
      env: 
        - WebpackiOS="12"
        - Type="Angular"
      osx_image: xcode10.2
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_script:
        - pod repo update
        - cd ../demo-angular && tns platform add ios@next
      script:
        - cd ../publish && sh pack.sh
        - cd ../demo-angular && npm i ../publish/package/*.tgz -s
        - tns build ios --bundle --env.uglify --env.aot
    - stage: "Test"
      env:
        - TestAndroid="21"
      language: android
      os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - cd ../demo && tns platform add android@next
      before_install:
        - nvm install 10
      script:  
        - cd ../publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build android
        - tns test android --justlaunch
    - os: osx
      env:
        - TestiOS="12"
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      osx_image: xcode10.2
      before_script:
        - pod repo update
        - cd ../demo && tns platform add ios@next
      script:
        - cd ../publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build ios
        - tns test ios --justlaunch 

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd demo
    - npm install tns-core-modules@next -P --save-exact
    - npm install tns-platform-declarations@next -D --save-exact
    - npm install nativescript-dev-webpack@next -D --save-exact
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - npx rimraf -- hooks node_modules platforms package-lock.json
    - cd ../demo-angular
    - npm install tns-core-modules@next -P --save-exact
    - npm install tns-platform-declarations@next -D --save-exact
    - npm install nativescript-angular@next -P --save-exact
    - npm install nativescript-dev-webpack@next -D --save-exact
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - ./node_modules/.bin/update-app-ng-deps
    - npx rimraf -- hooks node_modules platforms package-lock.json
