matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: 
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPackiOS="12"
        - Type="TypeScript"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPackAndroid="28"
        - Type="TypeScript"
      jdk: oraclejdk8
      before_install: nvm install 8
      script:  
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env: 
        - BuildAndroid="28"
        - Type="TypeScript"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script: 
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build android
    - os: osx
      env: 
        - BuildiOS="12"
        - Type="TypeScript"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build ios
    - language: android
      env: 
        - BuildAndroid="28"
        - Type="Angular"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script: 
        - cd publish && sh pack.sh
        - cd ../demo-angular && npm i ../publish/package/*.tgz -s
        - tns build android --bundle --env.uglify --env.snapshot --env.aot
    - os: osx
      env: 
        - BuildiOS="12"
        - Type="Angular"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd publish && sh pack.sh
        - cd ../demo-angular && npm i ../publish/package/*.tgz -s
        - tns build ios --bundle --env.uglify --env.aot
    - stage: "Test"
      env:
        - TestAndroid="28"
      language: android
      os: linux
      sudo: required
      jdk: oraclejdk8
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script:  
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build android
        - tns test android --justlaunch
    - os: osx
      env:
        - TestiOS="12"
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      osx_image: xcode10.0
      script: 
        - cd publish && sh pack.sh
        - cd ../demo && npm i ../publish/package/*.tgz -s
        - tns build ios
        - tns test ios --justlaunch 
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-28.0.3
    - android-26
    - android-28
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:	
    - sudo pip install --upgrade pip	
    - sudo pip install six	

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
